# Generated by Django 4.2.3 on 2023-07-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_PIN', models.CharField(max_length=100)),
                ('COMPANY_NAME', models.CharField(max_length=200)),
                ('ITAX_STATUS', models.CharField(max_length=100)),
                ('COMPANY_REG_STATUS', models.CharField(max_length=100)),
                ('PHYSICAL_LOCATION', models.TextField()),
                ('POSTAL_ADDRESS', models.TextField()),
                ('COMPANY_CONTACT', models.CharField(max_length=100)),
                ('BUSINESS_REG_NUM', models.CharField(max_length=100)),
                ('EMAIL_ADDRESS', models.EmailField(max_length=254)),
            ],
        ),
    ]
